### ISSUE TITLE
Better way to get entities

### ISSUE THREAD

**Issue by f0lie** [brandomr/ner2sna#1]
Instead of hacking together a function to glue NER tokens together, you can just ask CoreNLP to do it for you with `entitymentions`

```
In[2]:

output = nlp.annotate(text, properties={
  'annotators': 'entitymentions',
  'outputFormat': 'json'
  })
```
```
In[3]:

def proc_sentence(response):
    return [entity['text'] for sent in response['sentences'] for entity in sent['entitymentions']]
```

**Comment by brandomr** [comment]
You're a wizard! I was pretty sure that was possible just couldn't find the API docs to support it. Thanks for flagging. I'll incorporate it unless you'd like to make a PR.

**Comment by f0lie** [comment]
No problem. I don't think I have the time to write it a PR. This is more of a document than a library so I think the author should probably edit it.

I'll be closing this issue since it looks like the problem is solved.
